version: '3.8'
services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  rest_back:
    pull_policy: never
    depends_on:
      db:
        condition: service_started
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: rest_back
    env_file:
      - ./backend/.env
    ports:
      - '3000:3000'
  front:
    pull_policy: never
    depends_on:
      rest_back:
        condition: service_started
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: front
    env_file:
       - ./frontend/.env
    ports:
      - '8080:8087'
volumes:
  db:
    driver: local
