version: '3.8'
services:
  db:
    image: postgres:13-alpine
    restart: always
    env_file:
      - ./.env
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  rest_back:
    pull_policy: never
    depends_on:
      db:
        condition: service_started
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: rest_back
    env_file:
      - ./.env
    ports:
      - '3000:3000'
  front:
    pull_policy: never
    depends_on:
      rest_back:
        condition: service_started
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VUE_APP_BACK_URL=${VUE_APP_BACK_URL}
        - NODE_ENV_BACK_URL=${NODE_ENV_BACK_URL}
    image: front
    environment:
      VUE_APP_BACK_URL: ${VUE_APP_BACK_URL}
    env_file:
       - ./.env
    ports:
      - '8080:8087'
volumes:
  db:
    driver: local
